server:
  port: 8080
  servlet:
    context-path: /zuwa
    address: 10.7.88.152
#    address: 192.168.31.22
spring:

  profiles:
    active: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: mengxiaoheng
    url: jdbc:mysql://localhost:3306/zuwa_db?serverTimezone=GMT%2b8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 10240MB
